linters:
  enable-all: true
  disable:
# Disabling the following linters since are deprecated:
    - tenv
# Disabling the following linters since are not mostly adopted, eg:
# https://google.github.io/styleguide/go/decisions#external-context-vs-local-names
    - exhaustruct
    - varnamelen
    - tagliatelle
    - nilnil
  wsl:
    force-err-cuddling: true
    force-short-decl-cuddling: false
